<?php

namespace AppBundle\Repository;

/**
 * EcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByRecherche($recherche){
        $res = $this->getEntityManager()->createQuery(
            "SELECT e FROM AppBundle:Ecole e WHERE UPPER(e.patronyme) = UPPER('".$recherche. "') OR UPPER(e.nature) = UPPER('".$recherche. "') OR UPPER(e.academie) = UPPER('".$recherche. "')")->setMaxResults(500)->getResult();
        return $res;
    }
}
