<?php

namespace AppBundle\Repository;

/**
 * PollutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollutionRepository extends \Doctrine\ORM\EntityRepository
{
}
