<?php

namespace AppBundle\Repository;

/**
 * PollutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollutionRepository extends \Doctrine\ORM\EntityRepository
{
    public function genererGeoJSON($latitude, $longitude, $rayon){
            $json = "
                {
                \"type\": \"FeatureCollection\",
                \"features\": [";
                $listePoints = $this->executerSQL("CALL get_points_pollution($latitude, $longitude, $rayon);");
                foreach ($listePoints as $point) {
                $json .= "
                         {
                           \"type\": \"Feature\",
                           \"geometry\": {
                             \"type\": \"Point\",
                             \"coordinates\": [". strval($point["latitude"]) . ", " . strval($point["longitude"]) ."]
                           },
                           \"properties\": {
                             \"name\": \"Pollution ". $point["latitude"]."-".$point["longitude"] ."\"
                             }
                         },\n";
                }
                $json = substr($json, 0, -2);
                $json.= "\n]\n}";
                if (!$handle = fopen("geo.json", 'w')) {
                     echo "Impossible d'ouvrir le fichier (geo.json)";
                     exit;
                }
                if (fwrite($handle, $json) === FALSE) {
                    echo "Impossible d'écrire dans le fichier (geo.json)";
                    exit;
                }
                fclose($handle);
            return $json;
    }

    public function executerSQL($commandeSQL){

        return $this->getEntityManager()->getConnection()->executeQuery($commandeSQL)->fetchAll();
    }

}
