<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $res=$this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u ORDER BY u.id ASC'
            )
            ->getResult();
            //dump($res);
        return $res;
    }

    public function findAllOlderThan($dateTimestamp)
    {
        $res=$this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u WHERE u.createdAt > '.$dateTimestamp)
            ->getResult();
            dump('SELECT u FROM AppBundle:User u WHERE u.createdAt > '.$dateTimestamp);
            //dump($res);
        return $res;
    }
}
